### ISSUE TITLE
Made major changes to configs

### ISSUE THREAD

**Issue by Stereowalker** [Wabbit0101/mods_hoardercraft#122]
Could you update CarrotLib to support the latest version of Survive, I made changes to the config file i.e. rather than Config.enable_temperature.get(), it's now Config.enable_temperature

**Comment by Wabbit0101** [comment]
Will look into this later today.

**Comment by Wabbit0101** [comment]
Environment: **Dedicated Server 1.16.5**
Forge: **forge-1.16.5-36.0.1**
UnionLib mod: **UnionLib-1.16.5-3.2.3**
Survive mod: **Survive-1.16.5-3.1.2**
Serene Seasons: **SereneSeasons-1.16.4-4.0.0.86-universal**

I am unable to verify the fixes on a server due to the following error from UnionLib (A):
```
23.01 14:48:13 [Server] INFO [UnionLib Transformer]: Patching StructureStart...
23.01 14:48:13 [Server] INFO [UnionLib Transformer]:  Failed to apply patch 1
23.01 14:48:13 [Server] INFO [UnionLib Transformer]:  Successfully applied patch 2
23.01 14:48:13 [Server] INFO [UnionLib Transformer]: Patch for StructureStart#func_230366_a_ failed
```
AND this one which is killing all data pack loading from Survive (B) which stop server from starting (all tags are broken):
```
23.01 14:49:13 [Server] main/WARN [minecraft/Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
23.01 14:49:13 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.util.registry.DefaultedRegistry.func_212607_c(Lnet/minecraft/util/ResourceLocation;)Z
23.01 14:49:13 [Server] INFO at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:1.8.0_162] {}
23.01 14:49:13 [Server] INFO at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:1.8.0_162] {}
23.01 14:49:13 [Server] INFO at net.minecraft.server.Main.main(Main.java:130) ~[?:?] {re:classloading}
23.01 14:49:13 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162] {}
23.01 14:49:13 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162] {}
23.01 14:49:13 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162] {}
23.01 14:49:13 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162] {}
23.01 14:49:13 [Server] INFO at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.0.1.jar:36.0] {}
23.01 14:49:13 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
23.01 14:49:13 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
23.01 14:49:13 [Server] INFO at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
23.01 14:49:13 [Server] INFO at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
23.01 14:49:13 [Server] INFO at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
23.01 14:49:13 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.1.jar:?] {}
23.01 14:49:13 [Server] INFO at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.1.jar:?] {}
23.01 14:49:13 [Server] INFO at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.1.jar:?] {}
23.01 14:49:13 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.util.registry.DefaultedRegistry.func_212607_c(Lnet/minecraft/util/ResourceLocation;)Z
23.01 14:49:13 [Server] INFO at com.stereowalker.survive.resource.ItemDrinkDataManager.lambda$load$1(ItemDrinkDataManager.java:39) ~[?:1.16.5-3.1.2] {re:classloading}
23.01 14:49:13 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_162] {}
[snip]
```

Removing UnionLib+Survive and the server comes up fine with all other mods/settings the same. Note that things seem to work fine in Single Player (I have not tried LAN).

**Comment by Stereowalker** [comment]
I've fixed the UnionLib transformer issue in the latest version of UnionLib, and as for the Survive issue, I've changed the checking the vanilla registry to the forge one so as to iron out that issue

**Comment by Wabbit0101** [comment]
Verified Survive-1.16.5-3.1.3 works on server-only install as well now.
