### ISSUE TITLE
Rosewater rendering crash

### ISSUE THREAD

**Issue by ninjalol5** [Wabbit0101/mods_hoardercraft#138]
[crash-2021-08-24_13.42.54-client.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/7041539/crash-2021-08-24_13.42.54-client.txt)

As soon as I type ro in my search bar it crashes my log says something about the rosewater

**Comment by Wabbit0101** [comment]
Thanks for taking the time for the report; however, this is a crash is occuring in another mod -- pokecube. This looks like a capabilities attachment attempt associated with that mod is failing for some reason. Its being trigged from when Forge trying to associate capabilities with my item.

I recommend filing a bug with that mod. They can redirect back here if they have questions.

```
	at thut.api.item.ItemList.is(ItemList.java:40) ~[?:3.12.0] {re:classloading}
	at pokecube.legends.handlers.ItemHelperEffect.registerCapabilities(ItemHelperEffect.java:47) ~[?:3.12.0] {re:classloading}
	at pokecube.legends.handlers.ItemHelperEffect$$Lambda$14500/411240558.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2951/2002285602.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2549/650929057.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:597) ~[?:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:591) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
```
