### ISSUE TITLE
Game Crashes on world loading with Armor Underwear installed

### ISSUE THREAD

**Issue by AisuTistoto223** [Wabbit0101/mods_hoardercraft#81]
[crash-2019-10-11_19.52.50-server.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/3719999/crash-2019-10-11_19.52.50-server.txt)
java.lang.NoSuchFieldError: ENABLE_TEMPERATURE
	at org.jwaresoftware.mcmods.lib.integration.TANHelper.manageTemperature(TANHelper.java:130)
	at org.jwaresoftware.mcmods.lib.integration.TANHelper$LinedArmorModifier.applyPlayerModifiers(TANHelper.java:242)
	at toughasnails.temperature.TemperatureHandler.getPlayerTarget(TemperatureHandler.java:114)
	at toughasnails.temperature.TemperatureHandler.update(TemperatureHandler.java:66)
	at toughasnails.handler.ExtendedStatHandler.onPlayerTick(ExtendedStatHandler.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_769_ExtendedStatHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

![image](https://user-images.githubusercontent.com/47762838/66692189-e5a49300-ec69-11e9-91b1-94e16c96b11d.png)

![image](https://user-images.githubusercontent.com/47762838/66692192-ed643780-ec69-11e9-8958-5dfd55f5775c.png)

![image](https://user-images.githubusercontent.com/47762838/66692196-f35a1880-ec69-11e9-9ba4-8166c28b79b1.png)

**Comment by Wabbit0101** [comment]
This crash is inside of the Tough As Nails mod; what version of that mod are you using **EXACTLY**? I cannot tell from your screen shot so can't really see if it's a binary incompatibility (which is looks to be from the error being thrown from the JRE class loader).

**Comment by Wabbit0101** [comment]
Reopen if you provide more details as requested above.
